mongodb:
  urldb: localhost
  portdb: 27017

room-manager:
  url: http://localhost
  port: 7070
  time_out: 180
  urlenpoint: api/v1
  hostname_domain: server2012dc.arabitpro.local
  db: rmserver

ex-change:
  url: http://localhost
  port: 3000
  time_out: 180
  urlenpoint: api/v1
  hostname_domain: server2012dc.arabitpro.local
  db: exchangeservicedb

default_headers:
    exchange_calendar: Administrator@arabitpro.local
    content_type: application/json
