mongodb:
  urldb: localhost
  portdb: 27017

room-manager:
  url: localhost
  port: 7070
  time_out: 180
  urlenpoint: api/v1
  hostname_domain: server2012dc.arabitpro.local
  db: rmserver
  hostname: 10.28.124.134

ex-change:
  url: localhost
  port: 3000
  time_out: 180
  urlenpoint: api/v1
  hostname_domain: server2012dc.arabitpro.local
  hostname: 10.28.124.134
  db: exchangeservicedb

default_headers:
    protocol: http://
    exchange_credentials: QWRtaW5pc3RyYXRvcjpBQkMxMjN9
    exchange_calendar: Administrator@arabitpro.local
    content_type: application/json
    username: Administrator
    userpasword: ABC123}@

