Feature: Subscription

  @exchange @delete_suscription
  Scenario: Create a Subscription
    Given I request POST "subscriptions" with:
     """
        {
          "host": "localhost",
          "port": 7070,
          "notificationUrl": "/api/v1/notifications"
        }
     """
    And With the following headers:
      | Content-type | application/json|
    When I execute the request
    Then I expect status code 200
      And I verify data autogenerated in response is:
        |_id|
      And I verify that response built with request data is equal to JSON response


