@exchange  @deletebd
Feature: Subscription

 @functional
  Scenario: Create a Subscription
    Given I request POST "subscriptions" with:
     """
        {
          "host": "localhost",
          "port": 7070,
          "notificationUrl": "/api/v1/notifications"
        }
     """
    And With the following headers:
      | Content-type | application/json |
    When I execute the request
    Then I expect status code 200
    And the JSON should have 5 keys
    And The response header should exist
      | Content-type | application/json |
    And I verify data autogenerated in response is:
      | _id |
    And I verify that response built with request data is equal to JSON response

  @functional
  Scenario: Create a Subscription with an ip assigned to the machine
    Given I request POST "subscriptions" with:
     """
        {
          "host": "10.28.124.152",
          "port": 7070,
          "notificationUrl": "/api/v1/notifications"
        }
     """
    And With the following headers:
      | Content-type | application/json |
    When I execute the request
    Then I expect status code 200
    And the JSON should have 5 keys
    And The response header should exist
      | Content-type | application/json |
    And I verify data autogenerated in response is:
      | _id |
    And I verify that response built with request data is equal to JSON response

  @functional @create_subscription
  Scenario: Server doesn't accept create a subscription with a IP registered
    Given I request POST "subscriptions" with:
     """
        {
          "host": "localhost",
          "port": 7070,
          "notificationUrl": "/api/v1/notifications"
        }
     """
    And With the following headers:
      | Content-type | application/json |
    When I execute the request
    Then I expect status code 409
    And the JSON should be:
      """
          {
            "name": "ConflictValue",
             "description": "Conflict with a host with same name, the host needs to be unique."
          }
      """
  @functional
  Scenario Outline:Negative combinations for subscription scenarios
    Given I request POST "subscriptions" with:
      """
        {
          "host": <host>,
          "port": <ports>,
          "notificationUrl": <notificationUrls>
        }
     """
    And With the following headers:
      | Content-type | application/json |
    When I execute the request
    Then I expect status code <codes>

    Examples: No special characters in subscription
      | host        | ports               | notificationUrls        | codes |
      | 10101       | 7070                | "/api/v1/notifications" | 400   |
      | localhost   | 7070                | "/api/v1/notifications" | 400   |
      | ""          | 7070                | "/api/v1/notifications" | 400   |
      | "rrrrredg"  | 7070                | "/api/v1/notifications" | 400   |
      | "/()=?"     | 7070                | "/api/v1/notifications" | 400   |
      | "localhost" | 0                   | "/api/v1/notifications" | 400   |
      | "localhost" | "7070"              | "/api/v1/notifications" | 400   |
      | "localhost" |                     | "/api/v1/notifications" | 400   |
      | "localhost" | "-7070"             | "/api/v1/notifications" | 400   |
      | "localhost" | -7070               | "/api/v1/notifications" | 400   |
      | "localhost" | "%&/,"              | "/api/v1/notifications" | 400   |
      | "localhost" | "7070"              | "/api/v1/notifications" | 400   |
      | "localhost" | 4611686018427387903 | "/api/v1/notifications" | 400   |

    Examples: Special characters in subscription
      | host            | ports | notificationUrls        | codes |
      | "localhost"     | 7070  | "/api/v1/notifications" | 200   |
      | "localhost"     | 2     | "/api/v1/notifications" | 200   |
      | "10.28.124.152" | 7070  | "/api/v1/notifications" | 200   |

